// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1yWdKFEu1b-grIa-Gc3PwZida-KMbXSg',
    appId: '1:864294799345:web:d3613ab04793b1bf826650',
    messagingSenderId: '864294799345',
    projectId: 'notif1-d9ea4',
    authDomain: 'notif1-d9ea4.firebaseapp.com',
    storageBucket: 'notif1-d9ea4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGi9aJvKre_UFY3W9kZpI57kL3PXd2Ko',
    appId: '1:864294799345:android:cbe798d2b20edaf3826650',
    messagingSenderId: '864294799345',
    projectId: 'notif1-d9ea4',
    storageBucket: 'notif1-d9ea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUN5sImZHSBIJ_GgQpuAI0s9P-yoLzIE4',
    appId: '1:864294799345:ios:4f314eebaed9afc4826650',
    messagingSenderId: '864294799345',
    projectId: 'notif1-d9ea4',
    storageBucket: 'notif1-d9ea4.appspot.com',
    iosBundleId: 'com.example.notif1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUN5sImZHSBIJ_GgQpuAI0s9P-yoLzIE4',
    appId: '1:864294799345:ios:82b538c02cad9e45826650',
    messagingSenderId: '864294799345',
    projectId: 'notif1-d9ea4',
    storageBucket: 'notif1-d9ea4.appspot.com',
    iosBundleId: 'com.example.notif1.RunnerTests',
  );
}
